version: '3'

services:
  web:
    build: .
    ports:
      - "5005:5005"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_DEBUG=1
      - FLASK_RUN_PORT=5005
      - DATABASE_URI=mysql://username:password@db/requests

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: requests
      MYSQL_USER: username
      MYSQL_PASSWORD: password

volumes:
  mysql_data:

